# rates:
#   robot_state: 20.0
#   metrics: 0.04
#   lease: 1.0
#   front_image: 10.0
#   side_image: 10.0
#   rear_image: 10.0

# Reduce publishing frequency of images to improve state latency
rates:
  # Actual frequency will be lower than this.
  # It seems like the max actual frequency is around 25 Hz.
  robot_state: 40.0
  metrics: 1.0
  lease: 1.0
  front_image: 1.0
  side_image: 1.0
  rear_image: 1.0
auto_claim: True
auto_power_on: True
auto_stand: True
